title: Fed-A-Crate
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Fed-A-Crate
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Project website for Fed-A-Crate"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@4.1.0

exclude:
  - README.md
  - vendor
  - Gemfile

defaults:
# Define here page metadata attributes for all pages at once or on specific directories. More information: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  -
    scope:
      path: "pages/*"
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: false
  -
    scope:
      path: "pages/about/"
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: about
  -
    scope:
      path: "pages/best-practices/"
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: best-practices

theme_variables: 
  # git_host: GitHub
  # back_to_top: true
  # privacy_statement_url: /privacy
  # github_buttons: 
  #   position: top
  #   edit_me: true
  #   open_issue: true
  #   history: true
  # headings:
  #   related-pages: Related pages
  #   more-information-tiles: More information
  #   resource-table-all: Tools and resources on this page
  #   resource-table-all-collapse: false
  #   affiliation-tiles-page: Affiliations
  #   contributor-minitiles-page: Contributors
  # toc:
  #   min_headings: 2
  #   headings: 'h2'
  topnav:
    theme: dark
    brand_logo: assets/img/main_logo.svg
    # github: true
    # twitter: false
  theme_color: 42db70
  fonts:
    - https://fonts.googleapis.com/css2?family=Lilita+One:wght@200..800&display=swap


plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
#   source:
#     branch: main

